### PR TITLE
Autocompletition for metrics

### PR DESCRIPTION
**Pull request by fabiovincenzi**
Fixes https://github.com/G-Research/fasttrackml/issues/138.
Screenshot 2024-06-05 at 16 35 55
Screenshot 2024-06-05 at 16 36 01

### CODE REVIEW

**Comment by jescalada** [comment]
The autocompletion is snappy and works like a charm!

Just wondering about the actual query: It seems that when submitting the query we get a 500 error because the backend doesn't support parsing in the form of `metrics["metricName"]`. I wonder if there's a way to adapt the query to work directly with the current backend, otherwise we would have to extend the backend to support this dictionary-style access.

In any case, I think UI-wise this is good to go!

**Review by jescalada — APPROVED** [review]

**Comment by fabiovincenzi** [comment]
> The autocompletion is snappy and works like a charm!
> 
> Just wondering about the actual query: It seems that when submitting the query we get a 500 error because the backend doesn't support parsing in the form of `metrics["metricName"]`. I wonder if there's a way to adapt the query to work directly with the current backend, otherwise we would have to extend the backend to support this dictionary-style access.
> 
> In any case, I think UI-wise this is good to go!

@jescalada Thanks for the review! This is quite strange, It seems to be working on my side, are you using the latest version of the backend?

**Comment by jescalada** [comment]
@fabiovincenzi I thought that was the problem, but I'm still getting this with the latest commit in the backend (from 6 hours ago). This is the error I get:

image

I thought this might be due to running on Windows (and something weird happening when escaping the characters), but I'm running both the frontend and backend on Linux and a dev container respectively... Any thoughts?

**Comment by suprjinx** [comment]
I think @jescalada's error is a more general problem with handling syntax errors (the metrics subslicer needs something after it, like `.last > 0.1`).

Opened this ticket: https://github.com/G-Research/fasttrackml/issues/1264

**Review by suprjinx — APPROVED** [review]

**Pull request merged**
