### PR TITLE
Experiment Selection Header

### PR DESCRIPTION
**Pull request by jescalada**
Issues:
https://github.com/G-Research/fasttrackml/issues/862
https://github.com/G-Research/fasttrackml/issues/926

In this PR, I have added an `ExperimentBar` to all apps. It allows quick filtering of multiple experiments directly from the AppBar:

image

Behaviour:
- Every time an experiment is selected or deselected, backend is queried and relevant runs are fetched
- Experiments can be selected or deselected from the dropdown
- Experiments can be deselected directly from each `Chip`
- Experiment name on each `Chip` is shortened, hovering on it shows a tooltip with the full name
- Up to ~24 experiments can be selected at a given time without awkward styling issues
- **GLOBAL STATE:** Selected experiments persist when refreshing or switching apps

Issue:
- Bookmarking doesn't save the selected experiment names for that group, as the state is global
  - Might need to discuss/clarify how we want this to work (and patch it up in another ticket)

Remember to test across all tabs, as there may be some hidden bugs or edge cases that I haven't considered!

## Changelog:
- Add `ExperimentBar` component
  - Why: Doing everything on the existing `ExperimentHeader` would bloat it with unrelated stuff
- Add `ExperimentSelectionPopover` component
  - Why: For handling the multiple selection functionality which hasn't been done before
- Add `onSelectExperimentNamesChange` handler
- Perform API calls (`getMetricsData`, etc.) in `onSelectExperimentNamesChange` handlers in `createAppModel()`
  - Why: Data must be fetched from backend to reduce load on the UI
- Add shortened forms for experiment names on new components
- Add global state management for selectedExperimentNames via localStorage
  - Why: We want the experiment names to save across apps. localStorage was by far the easiest way to synchronize it without complicating the code or doing weird stuff with the app container
<details>

<summary>
Screenshots
</summary>

### No selection (default)
image

### Multiple selection with tooltip
image

### Query + Experiment Filtering
image

</details>

### CODE REVIEW

**Review by jgiannuzzi — COMMENTED** [review]
Great stuff @jescalada!

I had a very brief scroll of the PR and it looks like the experiment filtering is done on the client side instead of sending the filtered query to the server (`run.experiment in ['experiment_name_1', 'experiment_name_2']`). If that's the case, could you please switch it to server side filtering? The whole point of this header is to ensure that the UI has less data to handle than today.

Another important thing is that this should support selecting multiple experiments, as many users want to be able to compare runs across experiments. It looks like we may loose this ability in current version of your change?

**Comment by jescalada** [comment]
**Note:** I have just pushed some additional changes for:
- Adding global selected experiments state
- Simplifying the previous code

**Review by fabiovincenzi — COMMENTED** [review]
Good work! @jescalada 
I am having some problems using the Experiment Selection Header from the params tab, It shows the selected experiments and I can open the Popover but not adding or removing any of them.
Then I was wondering if we should even filter the params/metrics that we show on the metrics/params dropdown selectors, what do you think?

**Comment by jescalada** [comment]
> Good work! @jescalada I am having some problems using the Experiment Selection Header from the params tab, It shows the selected experiments and I can open the Popover but not adding or removing any of them. Then I was wondering if we should even filter the params/metrics that we show on the metrics/params dropdown selectors, what do you think?

Thanks for the review @fabiovincenzi! That's quite odd, what browser were you testing on? Is the console showing anything? The state should be set using the localStorage, so perhaps some permission issue there is preventing the state from getting updated? 🤔

**Comment by fabiovincenzi** [comment]
> > Good work! @jescalada I am having some problems using the Experiment Selection Header from the params tab, It shows the selected experiments and I can open the Popover but not adding or removing any of them. Then I was wondering if we should even filter the params/metrics that we show on the metrics/params dropdown selectors, what do you think?
> 
> Thanks for the review @fabiovincenzi! That's quite odd, what browser were you testing on? Is the console showing anything? The state should be set using the localStorage, so perhaps some permission issue there is preventing the state from getting updated? 🤔

Tested with Firefox and Safari, the console doesn't display anything it beave like nothing is triggered when clicking on it

**Review by fabiovincenzi — APPROVED** [review]
Looks really good!

**Pull request merged**
