### PR TITLE
Run Selector UX Improvements

### PR DESCRIPTION
**Pull request by jescalada**
This is a PR for improving the run selector for Metrics (https://github.com/G-Research/fasttrackml/issues/1031). It does not look too good when the number of lines exceeds 3, but users would have to select dozens of metrics for that to happen.

## Changelog
- Added support for multiple lines of selected metrics (allow wrapping in container)
- Shrunk the selected metric badges to increase the number of possible selected metrics
- Flipped the positions of the run query bar and the selected metrics

### No wrap:
image

### Wrap:
image

### CODE REVIEW

**Comment by jescalada** [comment]
Closing this PR as I compared against the wrong branch. 😓

**Comment by jescalada** [comment]
Thanks for switching the branch Fabio! :)

**Review by fabiovincenzi — COMMENTED** [review]
Maybe add a `max-height` for the box to limit this overflow when many metrics are selected?

**Comment by jescalada** [comment]
I added a scrollbar instead of increasing the size of the container. I also did the same for Params, so be sure to double check if that looks fine (personally, I feel the styling is a bit off and may require swapping the position of the query box for Params too...

**Review by suprjinx — APPROVED** [review]

**Pull request merged**
