### PR TITLE
Add Metrics filtering for Conditional Grouping

### PR DESCRIPTION
**Pull request by jescalada**
This PR adds Metrics to the list of fields we can filter conditionally for splitting charts. Because each run may have a different value for each metric, only the last value is considered when evaluating (as per Marin's suggestion).

Note that the conditional filtering is only available on the Metrics app at the moment.

### Changelog
- Add metrics to the list of selectable fields (`conditionalGroupingOptions`)
- Add metric filtering logic
  - Metrics are filtered based on the last logged value
- Add tooltip explaining metric filtering behaviour
- Shorten feature description on popup so it looks better on Google Chrome

### CODE REVIEW

**Review by fabiovincenzi — COMMENTED** [review]
Looks really good! 
I tryied a bit and I wasn't able to group by metric context, maybe I'm not using the right syntax.
Screenshot 2024-06-12 at 16 31 55

**Comment by jescalada** [comment]
Good catch Fabio! I'll take a look at it

**Comment by jescalada** [comment]
I managed to fix it by adding the context to the attributes to evaluate. I also double checked that there aren't any important attributes that we might want to put in there in the future. The issue with the duplicated entries was fixed by checking for unique values.

There is currently an issue with the metrics displaying as `metrics.undefined` on Firefox. That being said, I think it might be related to improper state being stored so I'd like to merge everything in first and test with a clean slate!

**Review by suprjinx — APPROVED** [review]
looks good -- is there a ticket/issue for the todo items?

**Comment by jescalada** [comment]
Just added one! https://github.com/G-Research/fasttrackml/issues/1295

**Pull request merged**
