### PR TITLE
Namespace Selector in AIM UI

### PR DESCRIPTION
**Pull request by fabiovincenzi**
Fixes https://github.com/G-Research/fasttrackml/issues/462

### CODE REVIEW

**Comment by fabiovincenzi** [comment]
Screenshot 2024-01-15 at 18 19 09
Screenshot 2024-01-15 at 18 19 14

**Comment by fabiovincenzi** [comment]
I agree with the Icon! @dsuhinin 
something like this:
Screenshot 2024-01-17 at 10 30 16
Screenshot 2024-01-17 at 10 30 37

**Comment by dsuhinin** [comment]
> I agree with the Icon! @dsuhinin something like this: Screenshot 2024-01-17 at 10 30 16 Screenshot 2024-01-17 at 10 30 37

yes, this way looks better for me and reasonable.

**Review by dsuhinin — APPROVED** [review]
Looks good for me!

**Comment by fabiovincenzi** [comment]
Now the tool tip shows the current namespace:
Screenshot 2024-01-18 at 10 25 53

**Review by dsuhinin — APPROVED** [review]

**Pull request merged**
